# tasks/main.yml
---

- name: Install epel-release
  yum:
    name: epel-release
    state: present
  when: install_python_requirements and ansible_distribution in ['CentOS', 'Fedora']

- name: Install pip
  yum:
    name: python2-pip
    state: present
  when: install_python_requirements and ansible_distribution in ['CentOS', 'Fedora']


- name: Install kubernetes package
  pip:
    name: kubernetes
  when: install_python_requirements and ansible_distribution in ['CentOS', 'Fedora']
